security:
    encoders:
        Intranet\MainBundle\Entity\User: 
            algorithm: bcrypt
            cost: 12
            
    providers:
        user_db:
            entity: { class: Intranet\MainBundle\Entity\User }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/security$
            security: false

        secured_area:
            pattern:    ^/*
            form_login:
                login_path: intranet_security
                check_path: intranet_security_login_check
                
            logout:
                path:   intranet_security_logout
           

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
