security:
    encoders:
        Intranet\MainBundle\Entity\User: 
            algorithm: sha512
            encode_as_base64: false
            iterations: 1
            
    providers:
        user_db:
            entity: { class: Intranet\MainBundle\Entity\User }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
            
        welcome:
            pattern:  ^/welcome/
            security: false    
            
        register:
            pattern:  ^/register/
            security: false
            
        register_action:
            pattern:  ^/register_action/
            security: false
        
        login:
            pattern:  ^/login/
            security: false
  
        secured_area:
            pattern:    ^/*
            form_login:
                login_path: intranet_login
                check_path: intranet_login_check
                
            logout:
                path:   intranet_logout
           

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
