intranet_main_homepage:
    pattern:  /
    defaults: { _controller: IntranetMainBundle:Index:index }

intranet_show_topic:
    pattern:  /topic/{topic_id}/
    defaults: { _controller: IntranetMainBundle:Topic:showTopic }
    
intranet_add_topic:
    pattern:  /topic/{topic_id}/add
    defaults: { _controller: IntranetMainBundle:Topic:addTopic }
        
intranet_post_topic_get_posts:
    pattern:  /posts/topic/{topic_id}/
    defaults: { _controller: IntranetMainBundle:PostTopic:getPosts }
    
intranet_post_office_get_posts:
    pattern:  /posts/office/{office_id}/
    defaults: { _controller: IntranetMainBundle:PostOffice:getPosts }
    
intranet_post_topic_add_post:
    pattern:  /posts/topic/{topic_id}/add/
    defaults: { _controller: IntranetMainBundle:PostTopic:addPost }
    
intranet_post_office_add_post:
    pattern:  /posts/office/{office_id}/add/
    defaults: { _controller: IntranetMainBundle:PostOffice:addPost }
    
intranet_post_topic_count:
    pattern:  /posts/topic/{topic_id}/count/
    defaults: { _controller: IntranetMainBundle:PostTopic:getPostsCount }
    
intranet_post_office_count:
    pattern:  /posts/office/{office_id}/count/
    defaults: { _controller: IntranetMainBundle:PostOffice:getPostsCount }
    
intranet_topic_members:
    pattern:  /topic/{topic_id}/members/
    defaults: { _controller: IntranetMainBundle:User:getTopicMembers }
    
intranet_office_members:
    pattern:  /office/{office_id}/members/
    defaults: { _controller: IntranetMainBundle:User:getOfficeMembers }
    
intranet_post_topic_new:
    pattern:  /posts/topic/{topic_id}/new/
    defaults: { _controller: IntranetMainBundle:PostTopic:getNewPosts }
    
intranet_post_office_new:
    pattern:  /posts/office/{office_id}/new/
    defaults: { _controller: IntranetMainBundle:PostOffice:getNewPosts }
    
intranet_security:
    pattern: /security
    defaults: { _controller: IntranetMainBundle:Security:index }
    
intranet_security_login_check:
    path: /security/login_check
    
intranet_security_logout:
    path: /security/logout
    
intranet_register:
    pattern:  /register/
    defaults: { _controller: IntranetMainBundle:User:addUser }
    
intranet_show_office:
    pattern:  /office/{office_id}
    defaults: { _controller: IntranetMainBundle:Office:showOffice }
    
intranet_add_office:
    pattern:  /office/{office_id}/add
    defaults: { _controller: IntranetMainBundle:Office:addOffice }
    
intranet_delete_office:
    pattern:  /office/{office_id}/delete
    defaults: { _controller: IntranetMainBundle:Office:deleteOffice }
    
intranet_delete_topic:
    pattern:  /topic/{topic_id}/delete
    defaults: { _controller: IntranetMainBundle:Topic:deleteTopic }
    
intranet_change_office_members:
    pattern:  /office/{office_id}/members/change
    defaults: { _controller: IntranetMainBundle:Office:changeOfficeMembers }
    
intranet_notifications_show:
    pattern:  /notifications/
    defaults: { _controller: IntranetMainBundle:Notification:showNotifications }
    
intranet_task_add:
    pattern:  /office/{office_id}/task/add/
    defaults: { _controller: IntranetMainBundle:Task:addTask }
    
intranet_task_edit:
    pattern:  /office/{office_id}/task/{task_id}/edit
    defaults: { _controller: IntranetMainBundle:Task:editTask }