intranet_main_homepage:
    pattern:  /
    defaults: { _controller: IntranetMainBundle:Index:index }

intranet_show_topic:
    pattern:  /topic/{topic_id}/
    defaults: { _controller: IntranetMainBundle:Topic:showTopic }
    
intranet_add_topic:
    pattern:  /topic/{topic_id}/add
    defaults: { _controller: IntranetMainBundle:Topic:addTopic }
        
intranet_post_topic_get_posts:
    pattern:  /posts/topic/{topic_id}/
    defaults: { _controller: IntranetMainBundle:PostTopic:getPosts }
    
intranet_post_office_get_posts:
    pattern:  /posts/office/{office_id}/
    defaults: { _controller: IntranetMainBundle:PostOffice:getPosts }
    
intranet_post_topic_add_post:
    pattern:  /posts/topic/{topic_id}/add/
    defaults: { _controller: IntranetMainBundle:PostTopic:addPost }
    
intranet_post_office_add_post:
    pattern:  /posts/office/{office_id}/add/
    defaults: { _controller: IntranetMainBundle:PostOffice:addPost }
    
intranet_post_topic_count:
    pattern:  /posts/topic/{topic_id}/count/
    defaults: { _controller: IntranetMainBundle:PostTopic:getPostsCount }
    
intranet_post_office_count:
    pattern:  /posts/office/{office_id}/count/
    defaults: { _controller: IntranetMainBundle:PostOffice:getPostsCount }
    
intranet_topic_members:
    pattern:  /topic/{topic_id}/members/
    defaults: { _controller: IntranetMainBundle:User:getTopicMembers }
    
intranet_office_members:
    pattern:  /office/{office_id}/members/
    defaults: { _controller: IntranetMainBundle:User:getOfficeMembers }
    
intranet_post_topic_new:
    pattern:  /posts/topic/{topic_id}/new/
    defaults: { _controller: IntranetMainBundle:PostTopic:getNewPosts }
    
intranet_post_office_new:
    pattern:  /posts/office/{office_id}/new/
    defaults: { _controller: IntranetMainBundle:PostOffice:getNewPosts }
    
intranet_security:
    pattern: /security
    defaults: { _controller: IntranetMainBundle:Security:index }
    
intranet_security_login_check:
    path: /security/login_check
    
intranet_security_logout:
    path: /security/logout
    
intranet_register:
    pattern:  /register/
    defaults: { _controller: IntranetMainBundle:User:addUser }
    
intranet_show_office:
    pattern:  /office/{office_id}
    defaults: { _controller: IntranetMainBundle:Office:showOffice }
    
intranet_add_office:
    pattern:  /office/{office_id}/add
    defaults: { _controller: IntranetMainBundle:Office:addOffice }
    
intranet_delete_office:
    pattern:  /office/{office_id}/delete
    defaults: { _controller: IntranetMainBundle:Office:deleteOffice }
    
intranet_delete_topic:
    pattern:  /topic/{topic_id}/delete
    defaults: { _controller: IntranetMainBundle:Topic:deleteTopic }
    
intranet_change_office_members:
    pattern:  /office/{office_id}/members/change
    defaults: { _controller: IntranetMainBundle:Office:changeOfficeMembers }
    
intranet_notifications_clear:     
    pattern:  /notifications/clear/
    defaults: { _controller: IntranetMainBundle:Notification:clearNotifications }
    
intranet_notifications_show:     
    pattern:  /notifications/
    defaults: { _controller: IntranetMainBundle:Notification:showNotifications }
    
intranet_notifications_get:
    pattern:  /notifications/get/
    defaults: { _controller: IntranetMainBundle:Notification:getNotifications }
    
intranet_task_add:
    pattern:  /office/{office_id}/task/add/
    defaults: { _controller: IntranetMainBundle:Task:addTask }
    
intranet_task_edit:
    pattern:  /task/{task_id}/edit/
    defaults: { _controller: IntranetMainBundle:Task:editTask }
    
intranet_task_remove:
    pattern:  /task/{task_id}/remove/
    defaults: { _controller: IntranetMainBundle:Task:removeTask }
    
intranet_task_get_for_office:
    pattern:  /office/{office_id}/tasks/
    defaults: { _controller: IntranetMainBundle:Task:getTasksForOffice }
    
intranet_task_get_for_topic:
    pattern:  /topic/{topic_id}/tasks/
    defaults: { _controller: IntranetMainBundle:Task:getTasksForTopic }
    
intranet_post_task_show:
    pattern:  /posts/task/{task_id}/show/
    defaults: { _controller: IntranetMainBundle:PostTask:showPosts }
    
intranet_post_task_get:
    pattern:  /posts/task/{task_id}/get/
    defaults: { _controller: IntranetMainBundle:PostTask:getPosts }
    
intranet_post_task_add:
    pattern:  /posts/task/{task_id}/add/
    defaults: { _controller: IntranetMainBundle:PostTask:addPost }
    
intranet_task_activity_logs_show:
    pattern:  /taskActivityLogs/
    defaults: { _controller: IntranetMainBundle:TaskActivityLog:showTaskActivityLogs }
    
intranet_task_activity_logs_get:
    pattern:  /taskActivityLogs/get/
    defaults: { _controller: IntranetMainBundle:TaskActivityLog:getTaskActivityLogs }
    
intranet_task_reporter:
    pattern:  /taskReporter/
    defaults: { _controller: IntranetMainBundle:TaskReporter:showTaskReporter }
    
intranet_task_reporter_query:
    pattern:  /taskReporter/query/
    defaults: { _controller: IntranetMainBundle:TaskReporter:queryReport }
    
intranet_task_resetNewCommentsCount:
    pattern:  /task/{task_id}/resetNewCommentsCount/
    defaults: { _controller: IntranetMainBundle:Task:resetNewComments }
    
intranet_user_settings:
    pattern:  /user/settings/
    defaults: { _controller: IntranetMainBundle:UserSettings:index }
    
intranet_add_topic_to_personal_page:
  pattern: /topic/{topic_id}/addTopicChatToNewWindowPersonalPage/
  defaults: { _controller: IntranetMainBundle:Topic:addTopicChatToNewWindowPersonal }
  
intranet_add_office_to_personal_page:
    pattern:  /office/{office_id}/addOfficeToPersonalPage/
    defaults: { _controller: IntranetMainBundle:Office:addOfficeChatToPersonal }
    
intranet_show_personal_page:
    pattern:  /showPersonalPage/
    defaults: { _controller: IntranetMainBundle:PersonalPage:showPersonalPage }
    
intranet_add_topic_to_exist_window_personal_page:
  pattern: /topic/{topic_id}/{window_id}/addTopicChatToExistWindowPersonalPage/
  defaults: { _controller: IntranetMainBundle:Topic:addTopicToExistWindowPersonalPage }
  
intranet_add_office_to_exist_window_personal_page:
  pattern: /office/{office_id}/{window_id}/addOfficeChatToExistWindowPersonalPage/
  defaults: { _controller: IntranetMainBundle:Office:addOfficeToExistWindowPersonalPage }
  
intranet_delete_window_from_personal_page:
  pattern: /{windowid}/deleteWindow/
  defaults: { _controller: IntranetMainBundle:PersonalPage:deleteWindowFromPersonalPage }

intranet_delete_tab_from_personal_page:
  pattern: /{id}/deleteTab/
  defaults: { _controller: IntranetMainBundle:PersonalPage:deleteTabFromPersonalPage }
  
intranet_add_office_to_dropdown:
  pattern: /office/{officeId}/{windowId}/addOfficeToDropdown/
  defaults: { _controller: IntranetMainBundle:Office:addOfficeToDropdown }
  
intranet_add_topic_to_dropdown:
  pattern: /topic/{topicId}/{windowId}/addTopicToDropdown/
  defaults: { _controller: IntranetMainBundle:Topic:addTopicToDropdown }