intranet_main_homepage:
    pattern:  /
    defaults: { _controller: IntranetMainBundle:Index:index }

intranet_show_section:
    pattern:  /section/{section_id}/
    defaults: { _controller: IntranetMainBundle:Index:showSection }